config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount ActionCable.server => "/cable"
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resources :characters, only: [:index, :show]
  resources :games, only: [:show, :create, :destroy] do
    resources :players, except: [:edit, :new]
    resources :lover_couples, only: [:create, :destroy]
    resources :messages, only: :create
    resources :game_events, only: [:create, :destroy]

    get "/role", to: "games#role"

    get "/cupidon", to: "lover_couples#cupidon"
    get "/random_couple_choose", to: "lover_couples#random_couple_choose"
    get "/voyante", to: "game_events#voyante"
    get "/voyante_next_step", to: "game_events#voyante_next_step"
    get "/loup", to: "game_events#loup"
    get "/random_loup_choose", to: "game_events#random_loup_choose"
    get "/sorciere", to: "game_events#sorciere"
    get "/random_sorciere_choose", to: "game_events#random_sorciere_choose"
    get "/chasseur", to: "game_events#chasseur"
    get "/random_chasseur_kill", to: "game_events#random_chasseur_kill"

    get "/when_day_comes", to: "game_events#when_day_comes"
    get "/when_night_comes", to: "game_events#when_night_comes"
    get "/when_night_talk", to: "game_events#when_night_talk"
    get "/end_game", to: "games#end_game"
    get "/couple", to: "games#couple"
    get "/reveal", to: "games#reveal"

    get "/night", to: "games#night"
    get "/day", to: "games#day"
  end

  get "/find", to: "players#find_game"
  get "/animation", to: "pages#animation"
end

app/models/game.rb
class Game < ApplicationRecord
  after_initialize :set_defaults, unless: :persisted?

  has_many :players, dependent: :destroy
  has_many :game_events
  has_many :users, through: :players
  has_many :characters, through: :players
  has_many :messages, dependent: :destroy
  has_many :lover_couples

  private

  def set_defaults
    self.round_step = "show-role"
    self.round = 0
    self.step = "waiting"
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def show
    @game = Game.find(params[:id])
    @message = Message.new

    @gamer = Player.where(user: current_user, game: @game).first
    all = @game.players
    @all_except_me = []
    @dead = []
    @all_alive = []
    all.each do |player|
      @all_except_me << player if player.user != current_user && player.is_alive
      @dead << player if player.user != current_user && player.is_alive == false
      @all_alive << player if player.is_alive
    end

    @sorciere = Player.where(game: @game, character: Character.where(name: "sorciere").first).first
    @voyante = Player.where(game: @game, character: Character.where(name: "voyante").first).first
    @cupidon = Player.where(game: @game, character: Character.where(name: "cupidon").first).first
    @chasseur = Player.where(game: @game, character: Character.where(name: "chasseur").first).first
    @loup1 = Player.where(game: @game, character: Character.where(name: "loup").first).first
    @loup2 = Player.where(game: @game, character: Character.where(name: "loup").last).first
  end

  def create
    @game = Game.new
  end

  def destroy
    @game = Game.find(params[:id])
    @game.destroy
    redirect_to root_path
  end

  def end_game
    @game = Game.find(params[:game_id])
    @gamer = Player.where(user: current_user, game: @game).first
    @chasseur = Player.where(game: @game, character: Character.where(name: "chasseur").first).first
    @sorciere = Player.where(game: @game, character: Character.where(name: "sorciere").first).first
    @voyante = Player.where(game: @game, character: Character.where(name: "voyante").first).first
    @cupidon = Player.where(game: @game, character: Character.where(name: "cupidon").first).first
    @loup1 = Player.where(game: @game, character: Character.where(name: "loup").first).first
    @loup2 = Player.where(game: @game, character: Character.where(name: "loup").last).first
    @lovers = @game.lover_couples.first

    current_user.update(points: current_user.points + @gamer.points) if current_user.points != nil
    current_user.update(points: @gamer.points) unless current_user.points != nil
    current_user.update(level: current_user.level + 1, points: current_user.points / 1000) if current_user.points != nil && current_user.points / 1000 > 1

    @alivewolves = []
    @aliveplayers = []
    @players = []
    @wolfs = []
    @allalive = []
    @game.players.each do |player|
      if player.is_alive
        @alivewolves << player if player.character.name == "loup"
        @aliveplayers << player if player.character.name != "loup"
        @allalive << player
      end
      @wolfs << player if player.character.name == "loup"
      @players << player if player.character.name != "loup"
    end
    @lovers = Player.where(game: @game, is_link: true)
  end

  def role
    @game = Game.find(params[:game_id])
    @gamer = Player.where(user: current_user, game: @game).first
    all = @game.players
    @all_except_me = []
    @dead = []
    all.each do |player|
      @all_except_me << player if player.user != current_user && player.is_alive
      @dead << player if player.user != current_user && player.is_alive == false
    end
  end

  def day
    @game = Game.find(params[:game_id])
    @gamer = Player.where(user: current_user, game: @game).first
    all = @game.players
    @all_except_me = []
    @dead = []
    all.each do |player|
      @all_except_me << player if player.user != current_user && player.is_alive
      @dead << player if player.user != current_user && player.is_alive == false
    end
    @voyante = Player.where(game: @game, character: Character.where(name: "voyante").first).first
  end

  def night
    @game = Game.find(params[:game_id])
    @gamer = Player.where(user: current_user, game: @game).first
    all = @game.players
    @all_except_me = []
    @dead = []
    all.each do |player|
      @all_except_me << player if player.user != current_user && player.is_alive
      @dead << player if player.user != current_user && player.is_alive == false
    end
    @voyante = Player.where(game: @game, character: Character.where(name: "voyante").first).first
    if GameEvent.where(game: @game, round: @game.round, event_type: "villageois-vote") != [] || @game.round == 0
      @game.update(round: @game.round + 1)
    end
  end

  def couple
    @game = Game.find(params[:game_id])
    @gamer = Player.where(user: current_user, game: @game).first
    all = @game.players
    @all_except_me = []
    @dead = []
    all.each do |player|
      @all_except_me << player if player.user != current_user && player.is_alive
      @dead << player if player.user != current_user && player.is_alive == false
    end
    @lovers = LoverCouple.where(game: @game).first
    @cupidon = Player.where(game: @game, character: Character.where(name: "cupidon").first).first
  end

  def reveal
    @game = Game.find(params[:game_id])
    @gamer = Player.where(user: current_user, game: @game).first
    all = @game.players
    @all_except_me = []
    @dead = []
    all.each do |player|
      @all_except_me << player if player.user != current_user && player.is_alive
      @dead << player if player.user != current_user && player.is_alive == false
    end
    @voyante = Player.where(game: @game, character: Character.where(name: "voyante").first).first
    @target = GameEvent.where(game: @game, actor: @voyante, event_type: "spy", round: @game.round).first.target
    @game.update(round_step: "loup")
  end
end

app/views/games/_defeatModal.html.erb
<h2>You lose :'|</h2>

app/views/games/_finished.html.erb
<p>TO DO</p>

app/views/games/_historique_chasseur.html.erb
<% i += 1 %>
<div class="cupidon-historique <% if i % 2 == 0%>paire <% else %>impaire<% end %>">
  <div class="character">
    <%= image_tag @chasseur.user.photo.url, class: "avatar" %>
    <%= image_tag @chasseur.character.photo.url, class: "player" %>
  </div>
  <div class="description">
    <% victime = GameEvent.find_by(round: j, game: @game, event_type: "chasseur-kill").target %>
    <h4><span class="bolder"><%= @chasseur.user.username.capitalize %></span> a tiré sa dernière balle sur <span class="bolder"><%= victime.user.username.capitalize %></span>, qui était <%= victime.character.name.capitalize %>.<% if victime.character.name == "loup" %> C'était judicieux de sa part ! <% else %> Ce n'était pas un choix judicieux... <% end %></h4>
  </div>
</div>

app/views/games/_player_number.html.erb
<h2 class="mj-text">Il manque 1 joueur...</h2>

app/views/games/_victoryModal.html.erb
<h1>You win !!</h1>

app/views/games/_waiting.html.erb
<div class="allplayers">
  <% @all_except_me.each do |player| %>
    <div class="player mx-2">
      <div class="player-photo">
        <% if player.user.photo.url != nil %>
          <%= image_tag player.user.photo.url, class: "avatar" %>
        <% else %>
          <%= image_tag "https://images.assetsdelivery.com/compings_v2/gmast3r/gmast3r1511/gmast3r151100776.jpg", class: "avatar" %>
        <% end %>
      </div>
      <div class="player-name">
        <p><%= player.user.username.capitalize %></p>
      </div>
    </div>
  <% end %>
</div>

app/views/games/end_game.html.erb
<div class="my-nav navbar navbar-expand-sm navbar-light navbar-lewagon maitre-head">
  <img src="https://image.noelshack.com/fichiers/2019/35/6/1567258841-meuf.gif" alt="" class="mj">
  <% if @game.news != nil && @game.news.include?('villag') %>
  <h2 class="mj-text">Les villageois gagnent !</h2>
  <% elsif @game.news != nil && @game.news.include?('wolf') %>
  <h2 class="mj-text">Les loups gagnent !</h2>
  <% else %>
  <h2 class="mj-text">Le couple gagne !</h2>
  <% end %>

  <div id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <%= link_to user_path(current_user)  do %>
            <% if current_user.photo.url != nil %>
            <%= image_tag current_user.photo.url, class: "avatar" %>
            <% else %>
            <%= image_tag "https://www.shareicon.net/data/128x128/2015/09/27/107947_doc_512x512.png", class: "avatar" %>
            <% end %>
          <% end %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>
<div class="allplayers">
  <% @game.players.each do |player| %>
    <% if player != @gamer %>
      <div class="player mx-2">
        <div class="player-photo">
          <%= image_tag player.character.photo.url, class: "avatar" %>
        </div>
        <div class="player-name">
          <p><%= player.user.username.capitalize %></p>
        </div>
      </div>
    <% end %>
  <% end %>
</div>
<div class="win_or_loose">
  <div class="info-game">
    <div class="photo">
      <div class="info"><p><%= @gamer.points || 0 %><br>points</p></div>
      <%= image_tag @gamer.character.photo.url, class: "character" %>
      <% if @gamer.points != nil && @gamer.points > 0 %>
      <img src="https://www.shareicon.net/data/128x128/2017/03/29/881758_cup_512x512.png" alt="" class="badge">
      <%= audio_tag("paperplanes.mp3", autoplay: true, controls: true, loop: false, hidden:true)  %>

      <% else %>
      <img src="https://www.shareicon.net/data/128x128/2016/09/26/835604_halloween_512x512.png" alt="" class="badge">
      <% end %>
    </div>
  </div>
</div>

<div class="my-restart-button my-3">
  <%= link_to find_path  do %>
    <img src="https://www.sccpre.cat/mypng/detail/95-958295_reset-button-restart-button-pixel-art.png" alt="", class="restart">
  <% end %>
</div>

<% i = 1 %>

<div class="historique">
  <% j = 1 %>
  <div class="titre mt-3"><h5 class="titre">Première nuit :</h5></div>
  <div class="cupidon-historique impaire mt-3">
    <div class="character">
      <%= image_tag @cupidon.user.photo.url, class: "avatar" %>
      <%= image_tag @cupidon.character.photo.url, class: "player" %>
    </div>
    <div class="description">
      <h4><span class="bolder"><%= @cupidon.user.username.capitalize %></span> a lié les deux amoureux : <span class="bolder"><%= @lovers[0].user.username.capitalize %></span> et <span class="bolder"><%= @lovers[1].user.username.capitalize %></span>, respectivement <%= @lovers[0].character.name.capitalize %> et <%= @lovers[1].character.name.capitalize %>.</h4>
    </div>
  </div>
  <% i += 1 %>
  <div class="cupidon-historique <% if i % 2 == 0%>paire <% else %>impaire<% end %>">
    <div class="character">
      <%= image_tag @voyante.user.photo.url, class: "avatar" %>
      <%= image_tag @voyante.character.photo.url, class: "player" %>
    </div>
    <div class="description">
      <% espionnage = GameEvent.find_by(actor: @voyante, game: @game, round: 1, event_type: "spy") %>
      <% if espionnage == nil %>
        <h4><span class="bolder"><%= @voyante.user.username.capitalize %></span> n'a espionné personne cette nuit là.</h4>
      <% else %>
        <h4><span class="bolder"><%= @voyante.user.username.capitalize %></span> a décidé, cette nuit là, d'espionner <span class="bolder"><%= espionnage.target.user.username.capitalize %></span> qui était <%= espionnage.target.character.name %>.</h4>
      <% end %>
    </div>
  </div>
  <% i += 1 %>
  <div class="cupidon-historique <% if i % 2 == 0%>paire <% else %>impaire<% end %>">
    <div class="character">
      <%= image_tag @loup1.user.photo.url, class: "avatar" %>
      <%= image_tag @loup2.user.photo.url, class: "avatar2" %>
      <%= image_tag @loup1.character.photo.url, class: "player" %>
    </div>
    <div class="description">
      <% victime = GameEvent.find_by(round: 1, game: @game, event_type: "loup-vote", actor: @loup1).target %>
      <h4>Les loups, <span class="bolder"><%= @loup1.user.username.capitalize %></span> et <span class="bolder"><%= @loup2.user.username.capitalize %></span>, ont dévoré durant la nuit <span class="bolder"><%= victime.user.username.capitalize %></span>, qui était <%= victime.character.name.capitalize %>.</h4>
    </div>
  </div>
  <% i += 1 %>
  <div class="cupidon-historique <% if i % 2 == 0%>paire <% else %>impaire<% end %>">
    <div class="character">
      <%= image_tag @sorciere.user.photo.url, class: "avatar" %>
      <%= image_tag @sorciere.character.photo.url, class: "player" %>
    </div>
    <div class="description">
      <% poison = GameEvent.find_by(actor: @sorciere, round: 1, game: @game, event_type: "sorciere-kill").target %>
      <h4><span class="bolder"><%= @sorciere.user.username.capitalize %></span> a empoisonné <span class="bolder"><%= poison.user.username.capitalize %></span>, qui était <%= poison.character.name.capitalize %>.<% if poison.character.name == "loup" %> C'est bien visé ! <% else %> Quel gachis ! <% end %></h4>
    </div>
  </div>
  <% if @chasseur.state_chasseur.include?(j.to_s) && @chasseur.state_chasseur.include?('start') %>
  <% i += 1 %>
  <div class="cupidon-historique <% if i % 2 == 0%>paire <% else %>impaire<% end %>">
    <div class="character">
      <%= image_tag @chasseur.user.photo.url, class: "avatar" %>
      <%= image_tag @chasseur.character.photo.url, class: "player" %>
    </div>
    <div class="description">
      <% victime = GameEvent.find_by(round: j, game: @game, event_type: "chasseur-kill").target %>
      <h4><span class="bolder"><%= @chasseur.user.username.capitalize %></span> a tiré sa dernière balle sur <span class="bolder"><%= victime.user.username.capitalize %></span>, qui était <%= victime.character.name.capitalize %>.<% if victime.character.name == "loup" %> C'était judicieux de sa part ! <% else %> Ce n'était pas un choix judicieux... <% end %></h4>
    </div>
  </div>
  <% end %>
  <% if GameEvent.find_by(round: 1, game: @game, event_type: "villageois-vote") != nil %>
  <% accusé = GameEvent.find_by(round: 1, game: @game, event_type: "villageois-vote").target %>
  <% i += 1 %>
  <div class="titre mt-3"><h5 class="titre">Premier jour :</h5></div>
  <div class="cupidon-historique <% if i % 2 == 0%>paire <% else %>impaire<% end %>">
    <div class="character">
      <img src="https://www.shareicon.net/data/128x128/2016/07/07/792192_envelope_512x512.png" alt="" class="player">
    </div>
    <div class="description">
      <h4>Les villageois ont voté pour la pendaison de <span class="bolder"><%= accusé.user.username.capitalize %></span>, qui était <%= accusé.character.name.capitalize %>.<% if accusé.character.name == "loup" %> Un bon point pour le village ! <% else %> Pauvre innocent<%if accusé.character.name == "sorciere" || accusé.character.name == "voyante" %>e<%end%>... <% end %></h4>
    </div>
  </div>
  <% end %>
  <% if @chasseur.state_chasseur.include?(j.to_s) && @chasseur.state_chasseur.include?('end') %>
  <% i += 1 %>
  <div class="cupidon-historique <% if i % 2 == 0%>paire <% else %>impaire<% end %>">
    <div class="character">
      <%= image_tag @chasseur.user.photo.url, class: "avatar" %>
      <%= image_tag @chasseur.character.photo.url, class: "player" %>
    </div>
    <div class="description">
      <% victime = GameEvent.find_by(round: j, game: @game, event_type: "chasseur-kill").target %>
      <h4><span class="bolder"><%= @chasseur.user.username.capitalize %></span> a tiré sa dernière balle sur <span class="bolder"><%= victime.user.username.capitalize %></span>, qui était <%= victime.character.name.capitalize %>.<% if victime.character.name == "loup" %> C'était judicieux de sa part ! <% else %> Ce n'était pas un choix judicieux... <% end %></h4>
    </div>
  </div>
  <% end %>
  <% j += 1 %>
  <% while(j <= @game.round) %>
    <div class="titre mt-3"><h5 class="titre"><% if j == 2 %>Seconde<%else%>Troisieme<%end%>  nuit :</h5></div>
    <% espionnage = GameEvent.find_by(actor: @voyante, game: @game, round: j, event_type: "spy") %>
    <% if espionnage != nil %>
    <% i += 1 %>
      <div class="cupidon-historique <% if i % 2 == 0%>paire <% else %>impaire<% end %>">
        <div class="character">
          <%= image_tag @voyante.user.photo.url, class: "avatar" %>
          <%= image_tag @voyante.character.photo.url, class: "player" %>
        </div>
        <div class="description">
          <h4><span class="bolder"><%= @voyante.user.username.capitalize %></span> a décidé, cette nuit là, d'espionner <span class="bolder"><%= espionnage.target.user.username.capitalize %></span> qui était <%= espionnage.target.character.name %>.</h4>
        </div>
      </div>
    <% end %>
    <% i += 1 %>
    <div class="cupidon-historique <% if i % 2 == 0%>paire <% else %>impaire<% end %>">
      <div class="character">
        <%= image_tag @loup1.user.photo.url, class: "avatar" %>
        <%= image_tag @loup2.user.photo.url, class: "avatar2" %>
        <%= image_tag @loup1.character.photo.url, class: "player" %>
      </div>
      <div class="description">
        <% victime = GameEvent.find_by(round: j, game: @game, event_type: "loup-vote", actor: @loup1).target %>
        <h4>Les loups, <span class="bolder"><%= @loup1.user.username.capitalize %></span> et <span class="bolder"><%= @loup2.user.username.capitalize %></span>, ont dévoré durant la nuit <span class="bolder"><%= victime.user.username.capitalize %></span>, qui était <%= victime.character.name.capitalize %>.</h4>
      </div>
    </div>
    <% if @chasseur.state_chasseur.include?(j.to_s) || GameEvent.find_by(round: j, game: @game, event_type: "villageois-vote") != nil %>
    <div class="titre mt-3"><h5 class="titre"><% if j == 2 %>Second<%else%>Troisieme<%end%> jour :</h5></div>
    <% end %>
    <% if @chasseur.state_chasseur.include?(j.to_s) && @chasseur.state_chasseur.include?('start') %>
    <% i += 1 %>
    <div class="cupidon-historique <% if i % 2 == 0%>paire <% else %>impaire<% end %>">
      <div class="character">
        <%= image_tag @chasseur.user.photo.url, class: "avatar" %>
        <%= image_tag @chasseur.character.photo.url, class: "player" %>
      </div>
      <div class="description">
        <% victime = GameEvent.find_by(round: j, game: @game, event_type: "chasseur-kill").target %>
        <h4><span class="bolder"><%= @chasseur.user.username.capitalize %></span> a tiré sa dernière balle sur <span class="bolder"><%= victime.user.username.capitalize %></span>, qui était <%= victime.character.name.capitalize %>.<% if victime.character.name == "loup" %> C'était judicieux de sa part ! <% else %> Ce n'était pas un choix judicieux... <% end %></h4>
      </div>
    </div>
    <% end %>
    <% if GameEvent.find_by(round: j, game: @game, event_type: "villageois-vote") != nil %>
    <% accusé = GameEvent.find_by(round: j, game: @game, event_type: "villageois-vote").target %>
    <% i += 1 %>
      <div class="cupidon-historique <% if i % 2 == 0%>paire <% else %>impaire<% end %>">
        <div class="character">
          <img src="https://www.shareicon.net/data/128x128/2016/07/07/792192_envelope_512x512.png" alt="" class="player">
        </div>
        <div class="description">
          <h4>Les villageois ont voté pour la pandaison de <span class="bolder"><%= accusé.user.username.capitalize %></span>, qui était <%= accusé.character.name.capitalize %>.<% if accusé.character.name == "loup" %> Un bon point pour le village ! <% else %> Pauvre innocent<%if accusé.character.name == "sorciere" || accusé.character.name == "voyante" %>e<%end%>... <% end %></h4>
        </div>
      </div>
    <% end %>
    <% if @chasseur.state_chasseur.include?(j.to_s) && @chasseur.state_chasseur.include?('end') %>
    <% i += 1 %>
    <div class="cupidon-historique <% if i % 2 == 0%>paire <% else %>impaire<% end %>">
      <div class="character">
        <%= image_tag @chasseur.user.photo.url, class: "avatar" %>
        <%= image_tag @chasseur.character.photo.url, class: "player" %>
      </div>
      <div class="description">
        <% victime = GameEvent.find_by(round: j, game: @game, event_type: "chasseur-kill").target %>
        <h4><span class="bolder"><%= @chasseur.user.username.capitalize %></span> a tiré sa dernière balle sur <span class="bolder"><%= victime.user.username.capitalize %></span>, qui était <%= victime.character.name.capitalize %>.<% if victime.character.name == "loup" %> C'était judicieux de sa part ! <% else %> Ce n'était pas un choix judicieux... <% end %></h4>
      </div>
    </div>
    <% end %>
    <% j += 1 %>
  <% end %>
</div>

<!-- EMPTY DIV EMBEDDING DATA -->
<div id="connect-to-game-channel" data-game-id="<%= @game.id %>" data-current-user-id="<%= current_user.id %>"></div>

app/views/games/role.html.erb
<div id="circle15"></div>
<div class="my-nav navbar navbar-expand-sm navbar-light navbar-lewagon maitre-head">
  <img src="https://image.noelshack.com/fichiers/2019/35/6/1567258841-meuf.gif" alt="" class="mj">
  <% if @gamer.character.name == "loup" %>
  <h2 class="mj-text">Ca sent la chair fraiche...</h2>
  <% elsif @gamer.character.name == "voyante" %>
  <h2 class="mj-text">Discretion est maitre mot !</h2>
  <% elsif @gamer.character.name == "sorciere" %>
  <h2 class="mj-text">La mort t'accompagne</h2>
  <% elsif @gamer.character.name == "cupidon" %>
  <h2 class="mj-text">Amour, quelle aventure !</h2>
  <% elsif @gamer.character.name == "chasseur" %>
  <h2 class="mj-text">Vengeance n'est point solution</h2>
  <% end %>

  <div id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <%= link_to user_path(current_user)  do %>
            <% if current_user.photo.url != nil %>
            <%= image_tag current_user.photo.url, class: "avatar" %>
            <% else %>
            <%= image_tag "https://www.shareicon.net/data/128x128/2015/09/27/107947_doc_512x512.png", class: "avatar" %>
            <% end %>
          <% end %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

<div class="allplayers">
  <% @all_except_me.each do |player| %>
    <div class="player mx-2">
      <div class="player-photo">
        <% if player.user.photo.url != nil %>
          <%= image_tag player.user.photo.url, class: "avatar" %>
        <% else %>
          <%= image_tag "https://images.assetsdelivery.com/compings_v2/gmast3r/gmast3r1511/gmast3r151100776.jpg", class: "avatar" %>
        <% end %>
      </div>
      <div class="player-name">
        <p><%= player.user.username.capitalize %></p>
      </div>
    </div>
  <% end %>
</div>

<div id="countdown"></div>

<div class="role">
  <div class="character">
    <%= image_tag @gamer.character.photo.url, class: "avatar" %>
  </div>
  <h4 class="info"> Tu es un<% if @gamer.character.name == "sorciere" || @gamer.character.name == "voyante"%>e<%end%> <%= @gamer.character.name %></h4>
  <div class="description">
    <h4><%= @gamer.character.description %></h4>
  </div>
</div>

<div class="other-role">
  <% Character.all.each do |character| %>
    <% if character.name != @gamer.character.name %>
      <div class="other-role-card">
        <div class="character">
          <%= image_tag character.photo.url %>
        </div>
        <div class="name">
          <p><%= character.name.capitalize %></p>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

<div id="connect-to-game-channel" data-game-id="<%= @game.id %>" data-current-user-id="<%= current_user.id %>"></div>
<div class="show-role"></div>

app/views/games/show.html.erb
<% if @game.step == "starting" %> <div id="circle3"></div> <% end %>
<div class="my-nav navbar navbar-expand-sm navbar-light navbar-lewagon maitre-head all-up">
  <img src="https://image.noelshack.com/fichiers/2019/35/6/1567258841-meuf.gif" alt="" class="mj">
  <% if @game.step == "waiting" %>
    <%= render 'player_number' %>
  <% elsif @game.step == "starting" %>
    <h2 class="mj-text">Place au débat</h2>
  <% else %>
    <h2 class="mj-text">La partie est terminée !</h2>
  <% end %>

  <div id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <%= link_to user_path(current_user)  do %>
              <% if @game.step == "starting" %>
                <% if @gamer.is_alive %>
                  <%= image_tag @gamer.character.photo.url, class: "avatar" %>
                <% else %>
                  <%= image_tag @gamer.character.photo.url, class: "filtered" %>
                <% end %>
              <% else %>
                <% if current_user.photo.url != nil %>
                <%= image_tag current_user.photo.url, class: "avatar" %>
                <% else %>
                <%= image_tag "https://www.shareicon.net/data/128x128/2015/09/27/107947_doc_512x512.png", class: "avatar" %>
                <% end %>
            <% end %>
          <% end %>
        </li>
      <% else %>
        <li class="nav-item">

        </li>
      <% end %>
    </ul>
  </div>
</div>

<% if @game.step == "waiting" %>
  <%= render "waiting" %>
<% elsif @game.step == "starting" %>
  <%= render "starting" %>
<% else %>
  <%= render "finished" %>
<% end %>

<!-- MAIN CHATROOM -->
<div class="container">
    <div id="messages" class="message-box">
    </div>
    <div class="message-form">
      <%= render 'messages/form', game: @game, message: @message, gamer: @gamer %>
  </div>
</div>


<!-- EMPTY DIV EMBEDDING DATA -->
<div id="connect-to-game-channel" data-game-id="<%= @game.id %>" data-current-user-id="<%= current_user.id %>"></div>
<div id="info-number-player-alive" data-number-id="<%= @all_except_me.count %>"></div>